# I had to change the plugin name because the underscore in the name is causing problems in Android NDK.
# Since I had previously uploaded the package with the old name, I must update it with that old name.
#name: flutter_opengl
name: flutteropengl
description: An early stage of Flutter OpenGL plugin. Only for Android for now.
version: 0.0.3
homepage: https://github.com/alnitak/flutter_opengl

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.bavagnoli.flutteropengl
    pluginClass: FlutteropenglPlugin
